# Generated by Django 2.2.7 on 2019-11-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bucketlist',
            new_name='HouseDetails',
        ),
    ]
